language: php

php:
    - 5.4
    - 5.5

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.3 WP_MULTISITE=0

before_script:
    - composer self-update
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit tests/testJetstashConnect.php
